API_PADRAO = 'http://127.0.0.1:5000/api/presenca'
API_GET_STATUS='http://127.0.0.1:5000/api/usuario'
API_ALARME='https://redoptimistictrust.vivf0.repl.co/api/usuario/status/alarme'
USUARIO='teste@teste.com'
SENHA='123'